export const CARD_TYPE_OPTIONS = ["CHARACTERS", "SPELL", "ACTION", "THEURGY", "ITEM"];

export const SEX_OPTIONS = ["MALE", "FEMALE", "UNKNOWN"];

export const ACTIVATION_ORDER_OPTIONS = [
  "END_COMBAT",
  "END_TURN",
  "BEGIN_TURN",
  "CARD_ACTIVATION",
];
export const AFFECTED_OPTIONS = [
  "PLAYER",
  "OPPONENT_PLAYER",
  "CARD",
  "ACTIVE_CHARACTER",
  "ACTIVE_OPPONENT_CHARACTER",
  "SELECTED_ALLIES",
  "SELECTED_OPPONENTS",
  "SELECTED",
  "ALL_OPPONENTS",
  "ALL_ALLIES",
];
export const OPERATION_OPTIONS = ["BUFF", "DEBUFF", "EQUALIZE", "DAMAGE"];

export const VALUE_AFFECTED_OPTIONS = [
  "VALUE",
  "ACTIVE_CHARACTER_SPIRIT",
  "ACTIVE_CHARACTER_MAX_ATACK",
  "ACTIVE_CHARACTER_MIN_ATACK",
  "ACTIVE_CHARACTER_DEFENCE",
  "ACTIVE_CHARACTER_LIFE",
  "SELECTED_CHARACTER_SPIRIT",
  "SELECTED_CHARACTER_MAX_ATACK",
  "SELECTED_CHARACTER_MIN_ATACK",
  "SELECTED_CHARACTER_DEFENCE",
  "SELECTED_CHARACTER_LIFE",
  "DISCARTED_CARDS",
];

export const STATUS_AFFECTED_OPTIONS = [
  "ATACK",
  "MIN_ATACK",
  "MAX_ATACK",
  "DEFENCE",
  "SPIRIT",
  "LIFE",
  "MAX_LIFE",
  "RACE",
  "CASTE",
  "CLASS",
  "LEVEL",
  "GUILD",
];

export const OPERATION_COMPARISSON_OPTIONS = [
  "LESS",
  "BIGGER",
  "EQUAL",
  "LESS_EQUAL",
  "BIGGER_EQUAL",
];